Feat: update sonarqube (#17)
* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

* feat: add sonarqube

diff --git a/sonarqube-dotnet/action.yml b/sonarqube-dotnet/action.yml
--- a/sonarqube-dotnet/action.yml
+++ b/sonarqube-dotnet/action.yml
@@ -50,23 +50,44 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: SonarQube Scan
-      uses: sonarsource/sonarqube-scan-action@v5.2.0
-      with:
-        args: >
-          -Dsonar.inclusions=**/*.cs
-          -Dsonar.sources=${{ inputs.sonar-sources }}
-          -Dsonar.projectBaseDir=${{ inputs.sonar-sources }}
-          -Dsonar.projectKey=${{ inputs.sonar-project-key }}
-          -Dsonar.projectName=${{ inputs.sonar-project-name }}
-          -Dsonar.cs.opencover.reportsPaths=${{ inputs.sonar-report-paths }}
-          -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
-          -Dsonar.scanner.skipSystemTruststore=true
-          -Dsonar.scanner.forceReload=true
-          -Dsonar.cs.analyzer.projectOutPaths=bin/Debug/net8.0
-      env:
-        SONAR_TOKEN: ${{ inputs.sonar-token }}
-        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
+    - name: Setup SonarScanner
+      shell: bash
+      run: |
+        # Install or update without failing if already installed
+        { dotnet tool update --global dotnet-sonarscanner || \
+        { [ $? -eq 0 ] || dotnet tool install --global dotnet-sonarscanner; }; } && \
+        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
+
+    - name: Verify SonarScanner
+      shell: bash
+      run: |
+        echo "SonarScanner path: $(which dotnet-sonarscanner)"
+        echo "Version: $(dotnet-sonarscanner --version)"
+
+    - name: Start SonarQube Analysis
+      shell: bash
+      run: |
+        dotnet-sonarscanner begin \
+        /k:"${{ inputs.sonar-project-key }}" \
+        /n:"${{ inputs.sonar-project-name }}" \
+        /d:sonar.host.url="${{ inputs.sonar-host-url }}" \
+        /d:sonar.login="${{ inputs.sonar-token }}" \
+        /d:sonar.cs.opencover.reportsPaths="${{ inputs.sonar-report-paths }}" \
+        /d:sonar.verbose="${{ inputs.sonar-verbose }}"
+
+    - name: Restore NuGet packages
+      shell: bash
+      run: dotnet restore ${{ inputs.sonar-project-name }}.sln
+
+    - name: Build Solution
+      shell: bash
+      run: dotnet build ${{ inputs.sonar-project-name }}.sln --no-restore
+
+    - name: End SonarQube Analysis
+      shell: bash
+      run: |
+        dotnet-sonarscanner end \
+          /d:sonar.login="${{ inputs.sonar-token }}"
 
     - name: Check SonarQube Quality Gate Status
       id: sonarqube-status
